/**
 * Surface detail for models that have no UVs.
 *
 * Every mesh here is generated by the Blender scripts out of primitives, and
 * none of them carry texture coordinates — 103 materials, all flat colour plus
 * a constant roughness. That is the single biggest reason the game reads as
 * untextured: a steel pauldron and a leather strap differ only in hue, so both
 * catch light like polished plastic.
 *
 * Unwrapping procedural geometry to fix that would mean UVs the Blender scripts
 * would have to regenerate — and re-unwrapping on every asset build is exactly
 * the kind of thing that drifts out of sync with the rig contract. So the detail
 * is *projected* instead: each pattern is sampled three times, along the object's
 * own X, Y and Z, and blended by how much the surface faces each axis. Triplanar
 * projection needs no UVs at all, and because it is keyed off object space the
 * pattern stays welded to the model as it animates.
 *
 * The maps themselves are generated here at load rather than shipped. They cost
 * nothing to download, which matters because the whole point of the meshopt pass
 * was to get the game under a couple of megabytes.
 */
import * as THREE from 'three';

const SIZE = 256;

/* ---------------------------------------------------------------- noise --- */

function hash2(x, y) {
  const s = Math.sin(x * 127.1 + y * 311.7) * 43758.5453;
  return s - Math.floor(s);
}

/** Value noise on a wrapping lattice, so every map tiles seamlessly. */
function valueNoise(x, y, period) {
  const xi = Math.floor(x), yi = Math.floor(y);
  const xf = x - xi, yf = y - yi;
  const u = xf * xf * (3 - 2 * xf);
  const v = yf * yf * (3 - 2 * yf);
  const w = (i, j) => hash2(((i % period) + period) % period,
    ((j % period) + period) % period);
  const a = w(xi, yi), b = w(xi + 1, yi);
  const c = w(xi, yi + 1), d = w(xi + 1, yi + 1);
  return (a * (1 - u) + b * u) * (1 - v) + (c * (1 - u) + d * u) * v;
}

function fbm(x, y, period, octaves) {
  let sum = 0, amp = 0.5, f = 1;
  for (let o = 0; o < octaves; o++) {
    sum += valueNoise(x * f, y * f, period * f) * amp;
    amp *= 0.5;
    f *= 2;
  }
  return sum;
}

/** Distance to the nearest of a wrapping grid of jittered points. */
function worley(x, y, cells) {
  const cx = Math.floor(x * cells), cy = Math.floor(y * cells);
  let best = 1e9;
  for (let j = -1; j <= 1; j++) {
    for (let i = -1; i <= 1; i++) {
      const gx = cx + i, gy = cy + j;
      const wx = ((gx % cells) + cells) % cells;
      const wy = ((gy % cells) + cells) % cells;
      const px = (gx + hash2(wx, wy)) / cells;
      const py = (gy + hash2(wy + 31.4, wx + 7.7)) / cells;
      const d = Math.hypot(x - px, y - py);
      if (d < best) best = d;
    }
  }
  return best * cells;
}

/* ------------------------------------------------------------- patterns --- */

/**
 * Each pattern returns a height in 0..1 for a point on the unit square, plus a
 * roughness offset. Height becomes a normal map by finite difference below;
 * the roughness offset breaks up the uniform sheen that makes everything look
 * like the same material painted different colours.
 */
const PATTERNS = {
  // Planished plate: broad shallow dents from the hammer, faint mill lines.
  steel: (x, y) => {
    const dents = 1 - worley(x, y, 5) * 0.5;
    const mill = Math.sin(y * Math.PI * 64) * 0.02;
    return { h: dents * 0.55 + fbm(x * 8, y * 8, 8, 3) * 0.25 + mill, r: (dents - 0.6) * 0.22 };
  },

  // Riveted mail: a dense staggered grid of rings.
  mail: (x, y) => {
    const rows = 26;
    const ry = y * rows;
    const row = Math.floor(ry);
    const offset = (row & 1) ? 0.5 : 0;         // stagger alternate rows
    const rx = (x * rows + offset);
    const fx = rx - Math.floor(rx) - 0.5;
    const fy = ry - row - 0.5;
    const d = Math.hypot(fx, fy) * 2;
    const ring = Math.max(0, 1 - Math.abs(d - 0.62) * 5);
    return { h: ring * 0.9 + 0.05, r: (0.5 - ring) * 0.3 };
  },

  // Cast and polished: gentle undulation, very little breakup.
  gold: (x, y) => {
    const s = fbm(x * 5, y * 5, 5, 3);
    return { h: s, r: (s - 0.5) * 0.16 };
  },

  // Leather: pebbled cells with cracks along the seams between them.
  leather: (x, y) => {
    const c = worley(x, y, 14);
    const crack = Math.max(0, 1 - c * 2.2);
    const grain = fbm(x * 26, y * 26, 26, 3) * 0.3;
    return { h: (1 - crack) * 0.7 + grain, r: crack * 0.34 };
  },

  // Fur: directional clumped streaks.
  fur: (x, y) => {
    const streak = fbm(x * 34, y * 5, 34, 3);
    return { h: streak, r: (streak - 0.5) * 0.4 };
  },

  // Woven cloth: an over-under warp and weft.
  cloth: (x, y) => {
    const n = 46;
    const warp = Math.sin(x * Math.PI * n);
    const weft = Math.sin(y * Math.PI * n);
    const weave = (warp > 0 ? warp : 0) * 0.5 + (weft > 0 ? weft : 0) * 0.5;
    return { h: weave * 0.7 + fbm(x * 12, y * 12, 12, 2) * 0.3, r: (0.5 - weave) * 0.26 };
  },

  // Quarried stone: coarse fractal pitting.
  stone: (x, y) => {
    const base = fbm(x * 6, y * 6, 6, 5);
    const pits = Math.max(0, 1 - worley(x, y, 9) * 1.6) * 0.4;
    return { h: base - pits, r: (base - 0.5) * 0.3 + pits * 0.2 };
  },

  // Sawn timber: long grain with occasional harder lines.
  wood: (x, y) => {
    const rings = Math.sin((y * 7 + fbm(x * 3, y * 12, 3, 3) * 2.4) * Math.PI * 2);
    const grain = fbm(x * 4, y * 40, 4, 3);
    return { h: rings * 0.28 + grain * 0.6, r: rings * 0.14 };
  },

  // Skin and bone: barely there, just enough to kill the plastic sheen.
  skin: (x, y) => {
    const s = fbm(x * 30, y * 30, 30, 3);
    return { h: s, r: (s - 0.5) * 0.18 };
  },
};

/** Builds an RGBA map: RGB is a tangent-space normal, A is roughness offset. */
function buildMap(fn) {
  const h = new Float32Array(SIZE * SIZE);
  const r = new Float32Array(SIZE * SIZE);
  for (let y = 0; y < SIZE; y++) {
    for (let x = 0; x < SIZE; x++) {
      const s = fn(x / SIZE, y / SIZE);
      h[y * SIZE + x] = s.h;
      r[y * SIZE + x] = s.r;
    }
  }

  const data = new Uint8Array(SIZE * SIZE * 4);
  const at = (x, y) => h[(((y % SIZE) + SIZE) % SIZE) * SIZE + (((x % SIZE) + SIZE) % SIZE)];
  for (let y = 0; y < SIZE; y++) {
    for (let x = 0; x < SIZE; x++) {
      // Central differences give the slope; the z term sets how pronounced it
      // is. Keep it around 1 so the normals stay shallow — this is meant to
      // read as grain under raking light, not as relief. Steep normals make
      // every surface catch the braziers at once, and the bloom pass then turns
      // the whole frame into an orange wash.
      const dx = at(x + 1, y) - at(x - 1, y);
      const dy = at(x, y + 1) - at(x, y - 1);
      let nx = -dx, ny = -dy, nz = 1.0;
      const len = Math.hypot(nx, ny, nz) || 1;
      nx /= len; ny /= len; nz /= len;
      const i = (y * SIZE + x) * 4;
      data[i] = (nx * 0.5 + 0.5) * 255;
      data[i + 1] = (ny * 0.5 + 0.5) * 255;
      data[i + 2] = (nz * 0.5 + 0.5) * 255;
      data[i + 3] = Math.max(0, Math.min(255, (r[y * SIZE + x] * 0.5 + 0.5) * 255));
    }
  }

  const tex = new THREE.DataTexture(data, SIZE, SIZE, THREE.RGBAFormat);
  tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
  tex.minFilter = THREE.LinearMipmapLinearFilter;
  tex.magFilter = THREE.LinearFilter;
  tex.generateMipmaps = true;
  tex.needsUpdate = true;
  return tex;
}

/* -------------------------------------------------------------- binding --- */

/**
 * How each family is projected and how hard the detail is pushed.
 * `scale` is in tiles per metre of object space — mail has to read as rings at
 * arm's length, stone as courses across a whole wall.
 */
const FAMILY = {
  // Armour and cloth are what the camera is nearest — in first person the
  // viewmodel is centimetres away — so these carry the detail harder than the
  // architecture does.
  steel:   { pattern: 'steel',   scale: 3.2,  normal: 0.36, rough: 0.16 },
  mail:    { pattern: 'mail',    scale: 11.0, normal: 0.58, rough: 0.20 },
  gold:    { pattern: 'gold',    scale: 4.5,  normal: 0.16, rough: 0.07 },
  leather: { pattern: 'leather', scale: 7.0,  normal: 0.40, rough: 0.20 },
  fur:     { pattern: 'fur',     scale: 6.0,  normal: 0.44, rough: 0.22 },
  cloth:   { pattern: 'cloth',   scale: 5.0,  normal: 0.30, rough: 0.14 },
  // The ground and the walls are the largest surfaces on screen, so they are
  // the least forgiving of an over-strong normal — kept deliberately gentle.
  stone:   { pattern: 'stone',   scale: 1.1,  normal: 0.24, rough: 0.13 },
  wood:    { pattern: 'wood',    scale: 2.2,  normal: 0.22, rough: 0.10 },
  skin:    { pattern: 'skin',    scale: 9.0,  normal: 0.12, rough: 0.07 },
};

/**
 * Material name -> family. The Blender scripts name every material after what
 * it is meant to be, which is what makes this possible without touching the
 * models. Order matters: `raider_heavy_mail` must match mail before leather.
 */
const RULES = [
  [/mail|chain/i, 'mail'],
  [/gold|brass|bronze/i, 'gold'],
  [/steel|iron|blade|jigane|dark$/i, 'steel'],
  [/leather|hide|strap|wrap|sack|rayskin/i, 'leather'],
  [/fur|hair/i, 'fur'],
  [/cloth|accent|lining|azure|crimson|cloak|tabard|straw/i, 'cloth'],
  [/stone|cobble|flagstone|mortar|wall|rubble|pillar|path|dirt|floor/i, 'stone'],
  [/timber|wood|haft|shaft/i, 'wood'],
  [/skin|bone|wax/i, 'skin'],
  // Padding and quilted black goods under the plate — dark, matte, leathery.
  [/black|gambeson|padding/i, 'leather'],
  [/charcoal|coal|ember/i, 'stone'],
];

/**
 * Surfaces that must stay perfectly smooth. Fire is a flat emissive card, and
 * perturbing its normal makes it flicker against the light rather than glow.
 */
const SMOOTH = /flame|fire|glow|spark/i;

export function classify(name = '') {
  if (SMOOTH.test(name)) return null;
  for (const [re, family] of RULES) if (re.test(name)) return family;
  return null;
}

/** Patterns are shared between every material that uses them. */
const cache = new Map();
function mapFor(pattern) {
  if (!cache.has(pattern)) cache.set(pattern, buildMap(PATTERNS[pattern]));
  return cache.get(pattern);
}

/**
 * Which materials already carry detail.
 *
 * Deliberately a WeakSet rather than a flag in `userData`: cloning a material
 * copies `userData` wholesale but drops `onBeforeCompile`, so a flag would mark
 * the clone as done while leaving it with no shader hook — every heraldry
 * surface would silently flatten and stay that way. A WeakSet is not copied, so
 * a clone correctly presents as untreated.
 */
const detailed = new WeakSet();

/**
 * Injects the triplanar lookup into a stock MeshStandardMaterial.
 *
 * The perturbation builds its own tangent frame from the geometric normal
 * rather than relying on a tangent attribute, which these models also lack.
 */
function enhance(material, family) {
  const cfg = FAMILY[family];
  if (!cfg || detailed.has(material)) return;
  detailed.add(material);
  // Public marker, for passes that merge materials by their lighting response:
  // two surfaces with the same roughness are no longer interchangeable once
  // each carries a different projected pattern. The WeakSet above stays the
  // authoritative guard, because this flag survives cloning and the hook does not.
  material.userData.detailed = true;

  const tex = mapFor(cfg.pattern);

  material.onBeforeCompile = (shader) => {
    shader.uniforms.uDetail = { value: tex };
    shader.uniforms.uDetailScale = { value: cfg.scale };
    shader.uniforms.uNormalAmp = { value: cfg.normal };
    shader.uniforms.uRoughAmp = { value: cfg.rough };

    shader.vertexShader = `varying vec3 vDetailPos;\nvarying vec3 vDetailNrm;\n${
      shader.vertexShader.replace(
        '#include <begin_vertex>',
        '#include <begin_vertex>\n\tvDetailPos = position;\n\tvDetailNrm = normal;',
      )}`;

    const header = `
      varying vec3 vDetailPos;
      varying vec3 vDetailNrm;
      uniform sampler2D uDetail;
      uniform float uDetailScale;
      uniform float uNormalAmp;
      uniform float uRoughAmp;

      // Three projections is the whole cost of this technique, so it is taken
      // once per fragment and shared. Roughness is resolved before normals in
      // the standard shader, which is why the sample lives at that injection
      // point and the normal pass simply reads it back.
      vec4 gDetail;

      vec4 sampleDetail() {
        vec3 p = vDetailPos * uDetailScale;
        vec3 b = pow(abs(normalize(vDetailNrm)), vec3(4.0));
        b /= max(b.x + b.y + b.z, 1e-4);
        return texture2D(uDetail, p.yz) * b.x
             + texture2D(uDetail, p.xz) * b.y
             + texture2D(uDetail, p.xy) * b.z;
      }
    `;

    shader.fragmentShader = header + shader.fragmentShader
      .replace(
        '#include <roughnessmap_fragment>',
        `#include <roughnessmap_fragment>
        gDetail = sampleDetail();
        roughnessFactor = clamp(
          roughnessFactor + (gDetail.a - 0.5) * 2.0 * uRoughAmp, 0.04, 1.0);`,
      )
      .replace(
        '#include <normal_fragment_maps>',
        `#include <normal_fragment_maps>
        {
          vec3 dn = gDetail.rgb * 2.0 - 1.0;
          vec3 N = normalize(normal);
          // Any vector not parallel to N gives a usable tangent frame; these
          // models carry no tangent attribute to derive a real one from.
          vec3 up = abs(N.y) < 0.99 ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);
          vec3 T = normalize(cross(up, N));
          vec3 B = cross(N, T);
          normal = normalize(N + (T * dn.x + B * dn.y) * uNormalAmp);
        }`,
      );
  };

  // Without this three reuses one compiled program for every material that
  // shares a cache key, and every family would end up with the first pattern.
  material.customProgramCacheKey = () => `detail:${family}`;
  material.needsUpdate = true;
}

/**
 * Walks a loaded scene and gives every recognised material its surface detail.
 * Returns how many were matched, so a rename in the Blender scripts that
 * silently stops matching shows up instead of quietly flattening the game.
 */
/**
 * Re-applies detail to a single material. Call this after cloning one — the
 * clone arrives without its shader hook. See the note on `detailed` above.
 */
export function detailMaterial(material) {
  if (!material?.isMeshStandardMaterial) return;
  const family = classify(material.name);
  if (family) enhance(material, family);
}

export function detailScene(root) {
  let matched = 0;
  const missed = new Set();
  root.traverse((o) => {
    if (!o.isMesh) return;
    for (const m of Array.isArray(o.material) ? o.material : [o.material]) {
      if (!m || !m.isMeshStandardMaterial) continue;
      const family = classify(m.name);
      if (family) { enhance(m, family); matched++; }
      else if (m.name && !SMOOTH.test(m.name)) missed.add(m.name);
    }
  });
  return { matched, missed: [...missed] };
}
